global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'internet-store'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['store-user-service-1:8081']
        labels:
          service: 'user-service'
      - targets: ['store-product-service-1:8082']
        labels:
          service: 'product-service'
      - targets: ['store-order-service-1:8083']
        labels:
          service: 'order-service'
      - targets: ['store-email-service-1:8085']
        labels: 
          service: 'email-service'
          
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'spring-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [store-user-service-1:8081', 'store-product-service-1:8082', 'store-order-service-1:8083', 'store-email-service-1:8085']

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
 
